### ISSUE TITLE
Not able to use it with webdriverio

### ISSUE THREAD

**Issue by mrbuddy** [fijijavis/wdio-json-reporter#24]
I am not able to use this reporter as part of webdriverio library. 

Just followed the steps from Readme

 **- npm install wdio-json-reporter
 - Updated wdio.conf with reporters: ['json']**

When I try to run my specs, I am seeing this error TypeError: ReporterClass is not a constructor.

Stacktrace:
[0-0] 2019-03-15T10:46:10.613Z ERROR @wdio/local-runner: Failed launching test session: TypeError: ReporterClass is not a constructor
    at BaseReporter.initReporter (/Users/Buddy/Documents/MobileAutomation/JSONReporter/node_modules/@wdio/runner/build/reporter.js:193:14)
    at Array.map (<anonymous>)
    at new BaseReporter (/Users/Buddy/Documents/MobileAutomation/JSONReporter/node_modules/@wdio/runner/build/reporter.js:34:39)
    at Runner.run (/Users/Buddy/Documents/MobileAutomation/JSONReporter/node_modules/@wdio/runner/build/index.js:89:21)
    at process.on.m (/Users/Buddy/Documents/MobileAutomation/JSONReporter/node_modules/@wdio/local-runner/build/run.js:37:20)
    at process.emit (events.js:194:15)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Please correct if I am wrong. Is it something that the runner expects it as a class before this module makes class using babel-runner?

**Comment by fijijavis** [comment]
@mrbuddy please see #36

**Comment by asheeshsingh2014** [comment]
@fijijavis - I was able to test this with v5. I see wdio-0-0-json-reporter.log being created with a JSON of test results. Similarly wdio-0-1-json-reporter.log for the second browser instance. 
*-json-reporter.log is being created for every browser instance running the spec.

As far as I remember this reporter used to spit out a results.json single file with all the tests & suites grouped?

**Comment by fijijavis** [comment]
published v1.0.0 of the reporter for compatibility with WDIO v5

**Comment by raketenolli** [comment]
Bug persists with "wdio-json-reporter": "^1.3.1"

```
ERROR @wdio/local-runner: Failed launching test session: TypeError: ReporterClass is not a constructor
    at BaseReporter.initReporter (C:\...\node_modules\@wdio\runner\build\reporter.js:124:14)
    at Array.map (<anonymous>)
    at new BaseReporter (C:\...\node_modules\@wdio\runner\build\reporter.js:32:39)
    at Runner.run (C:\...\node_modules\@wdio\runner\build\index.js:68:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by akanksha-1605** [comment]
I am also facing the same issue. Please help!
